version: '3'

services:

  ################################################################
  # reverse-proxy service definition
  reverse-proxy:
    restart: always

    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api
      - --providers.docker
      - --certificatesresolvers.le.acme.email=guillermoalvarado89@gmail.com
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json

    networks:
      - backend

    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.covidmex.live`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=admin:$$apr1$$B0tBWigX$$pKr/ibQVrwBoNfjLRT29i/"
      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
       # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Enable gzip compression
      - "traefik.http.middlewares.test-compress.compress=true"

  ################################################################
  # covidmex service definition
  covidmex:
    restart: always
    image: covidmex:latest
    build:
      context: .
      dockerfile: Dockerfile.covidmex

    environment:
      MYSQL_DB: 'covidmex_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'my-secret-pw'
      MYSQL_HOST: 'covidmex-mysql'
      COVIDMEX_ENVIRONMENT: development
      COVIDMEX_ADMIN_PASSWORD: d9f8ej3s
      COVIDMEX_ADMIN_USER: admin

    #ports:
    #  - '80:80'

    depends_on:
      - covidmex-mysql

    networks:
      - backend

    labels:
      - traefik.http.routers.covidmex.rule=Host(`covidmex.live`)
      - traefik.http.routers.covidmex.tls.certresolver=le
      - traefik.http.routers.covidmex.tls=true
      - traefik.http.routers.covidmex.entrypoints=websecure

  ################################################################
  # covidmex-mysql service definition
  covidmex-mysql:
    restart: always
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

    networks:
      - backend

networks:
  backend:
    driver: bridge

