CREATE TABLE IF NOT EXISTS entidades(
   CLAVE_ENTIDAD      INTEGER  NOT NULL PRIMARY KEY 
  ,ENTIDAD_FEDERATIVA VARCHAR(31) NOT NULL
  ,ABREVIATURA        VARCHAR(3) NOT NULL
);
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (01,'AGUASCALIENTES','AS');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (02,'BAJA CALIFORNIA','BC');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (03,'BAJA CALIFORNIA SUR','BS');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (04,'CAMPECHE','CC');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (05,'COAHUILA DE ZARAGOZA','CL');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (06,'COLIMA','CM');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (07,'CHIAPAS','CS');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (08,'CHIHUAHUA','CH');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (09,'CIUDAD DE MÉXICO','DF');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (10,'DURANGO','DG');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (11,'GUANAJUATO','GT');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (12,'GUERRERO','GR');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (13,'HIDALGO','HG');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (14,'JALISCO','JC');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (15,'MÉXICO','MC');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (16,'MICHOACÁN DE OCAMPO','MN');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (17,'MORELOS','MS');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (18,'NAYARIT','NT');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (19,'NUEVO LEÓN','NL');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (20,'OAXACA','OC');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (21,'PUEBLA','PL');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (22,'QUERÉTARO','QT');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (23,'QUINTANA ROO','QR');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (24,'SAN LUIS POTOSÍ','SP');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (25,'SINALOA','SL');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (26,'SONORA','SR');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (27,'TABASCO','TC');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (28,'TAMAULIPAS','TS');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (29,'TLAXCALA','TL');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (30,'VERACRUZ DE IGNACIO DE LA LLAVE','VZ');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (31,'YUCATÁN','YN');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (32,'ZACATECAS','ZS');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (36,'ESTADOS UNIDOS MEXICANOS','EUM');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (97,'NO APLICA','NA');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (98,'SE IGNORA','SI');
INSERT INTO entidades(CLAVE_ENTIDAD,ENTIDAD_FEDERATIVA,ABREVIATURA) VALUES (99,'NO ESPECIFICADO','NE');