CREATE TABLE IF NOT EXISTS nacionalidad(
   CLAVE       INTEGER  NOT NULL PRIMARY KEY 
  ,DESCRIPCION VARCHAR(15) NOT NULL
);
INSERT INTO nacionalidad(CLAVE,DESCRIPCION) VALUES (1,'MEXICANA');
INSERT INTO nacionalidad(CLAVE,DESCRIPCION) VALUES (2,'EXTRANJERA');
INSERT INTO nacionalidad(CLAVE,DESCRIPCION) VALUES (99,'NO ESPECIFICADO');
