CREATE TABLE IF NOT EXISTS resultado(
   CLAVE       INTEGER  NOT NULL PRIMARY KEY 
  ,DESCRIPCION VARCHAR(100) NOT NULL
);
INSERT INTO resultado(CLAVE,DESCRIPCION) VALUES (1,'Positivo SARS-CoV-2');
INSERT INTO resultado(CLAVE,DESCRIPCION) VALUES (2,'No positivo SARS-CoV-2');
INSERT INTO resultado(CLAVE,DESCRIPCION) VALUES (3,'Resultado pendiente');