CREATE TABLE IF NOT EXISTS sector(
   CLAVE       INTEGER  NOT NULL PRIMARY KEY 
  ,DESCRIPCION VARCHAR(100) NOT NULL
);
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (1,'CRUZ ROJA');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (2,'DIF');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (3,'ESTATAL');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (4,'IMSS');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (5,'IMSS-BIENESTAR');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (6,'ISSSTE');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (7,'MUNICIPAL');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (8,'PEMEX');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (9,'PRIVADA');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (10,'SEDENA');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (11,'SEMAR');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (12,'SSA');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (13,'UNIVERSITARIO');
INSERT INTO sector(CLAVE,DESCRIPCION) VALUES (99,'NO ESPECIFICADO');