CREATE TABLE IF NOT EXISTS sexo(
   CLAVE       INTEGER  NOT NULL PRIMARY KEY 
  ,DESCRIPCION VARCHAR(50) NOT NULL
);
INSERT INTO sexo(CLAVE,DESCRIPCION) VALUES (1,'MUJER');
INSERT INTO sexo(CLAVE,DESCRIPCION) VALUES (2,'HOMBRE');
INSERT INTO sexo(CLAVE,DESCRIPCION) VALUES (99,'NO ESPECIFICADO');