CREATE TABLE IF NOT EXISTS tipo_paciente(
   CLAVE       INTEGER  NOT NULL PRIMARY KEY 
  ,DESCRIPCION VARCHAR(50) NOT NULL
);
INSERT INTO tipo_paciente(CLAVE,DESCRIPCION) VALUES (1,'AMBULATORIO');
INSERT INTO tipo_paciente(CLAVE,DESCRIPCION) VALUES (2,'HOSPITALIZADO');
INSERT INTO tipo_paciente(CLAVE,DESCRIPCION) VALUES (99,'NO ESPECIFICADO');